CREATE TABLE IF NOT EXISTS endpoint_hit (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
app VARCHAR(255) NOT NULL,
uri VARCHAR(2048) NOT NULL,
ip VARCHAR(45) NOT NULL,
time_stamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_endpoint_hit_uri ON endpoint_hit(uri);
CREATE INDEX idx_endpoint_hit_time ON endpoint_hit(time_stamp);